BEGIN;
ALTER TYPE mark_component_type ADD VALUE IF NOT EXISTS 'CT1';
ALTER TYPE mark_component_type ADD VALUE IF NOT EXISTS 'CT2';
ALTER TYPE mark_component_type ADD VALUE IF NOT EXISTS 'CT3';
ALTER TYPE mark_component_type ADD VALUE IF NOT EXISTS 'ENDSEMESTER';
ALTER TYPE mark_component_type ADD VALUE IF NOT EXISTS 'MODELLAB';
ALTER TYPE mark_component_type ADD VALUE IF NOT EXISTS 'ENDSEMESTERLAB';
COMMIT;
